spring:
  application:
    name: identity
  profiles:
    active: dev
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:9090
  config:
    import: "configserver:"
  cloud:
    config:
      uri: http://localhost:8888
#    stream:
#      kafka:
#        binder:
#          brokers: 136.228.158.126:9092
#    bus:
#      trace:
#        enabled: true
#      refresh:
#        enabled: true
#      env:
#        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
logging:
  level:
    org:
      springframework:
        security: debug
        web: debug
server:
  port: 8899